"""create column uupdated_at in users table default

Revision ID: 003586f53ead
Revises: c2683d9a7ca0
Create Date: 2025-01-12 18:55:29.233925

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '003586f53ead'
down_revision: Union[str, None] = 'c2683d9a7ca0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
